spring:
  application:
    name: microservice-config-server
  profiles:
    active: native # \u672C\u5730\u914D\u7F6E

    # \u53EF\u4EE5\u6DFB\u52A0git \u914D\u7F6E\u548Csvn\u914D\u7F6E
#     cloud:
#        config:
#          server:
#            git:
#              uri: https://github.com/luoyefeiwu/learn_springcloud
#              username:
#              password:
#              search-paths: respo
#          label: master
server:
  port: 8888